### PR TITLE
Localization

### PR DESCRIPTION
**Pull request by irismolinari**
Add Italian language and remove unused locales

### CODE REVIEW

**Comment by irismolinari** [comment]
Specs need to be updated in order to be independent from the selected localization.

Some strings need to be localized, they were hardcoded in the views.

@sigfrid how would you like to translate the word entry? Is it ok 'registrazione'?

**Comment by sigfrid** [comment]
Isn't simpler (and faster) to always use `:en` in the test environment? 

'Registrazione' is fine.

**Comment by sigfrid** [comment]
So the app is now fully localized in both English and Italian. Correct?

**Comment by irismolinari** [comment]
Yes, we have both English and Italian localization. The default one is Italian.

**Pull request merged**
